# Generated by Django 4.1 on 2024-03-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
        ('Settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=90)),
                ('identification', models.CharField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.subregion')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.country')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities_light.region')),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Settings.idtype')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('reference', models.CharField(max_length=20)),
                ('status', models.BooleanField()),
                ('sale_price', models.FloatField()),
                ('gain_business', models.FloatField()),
                ('gain_operational', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Providers.provider')),
            ],
        ),
    ]
