# Generated by Django 4.1 on 2024-02-16 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
