# Generated by Django 4.1 on 2024-02-19 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_distributionproducttype'),
        ('Providers', '0002_remove_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='distribution_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Settings.distributionproducttype'),
            preserve_default=False,
        ),
    ]
