# Generated by Django 4.1 on 2024-03-03 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Settings', '0002_distributionproducttype'),
        ('Providers', '0003_product_distribution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='distribution_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Settings.distributionproducttype'),
        ),
        migrations.AlterField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Providers.provider'),
        ),
    ]
