# Generated by Django 4.1 on 2024-03-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Providers.product')),
                ('input', models.IntegerField()),
                ('output', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('operation_type', models.CharField(max_length=20)),
                ('operation_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
