# Generated by Django 4.1 on 2024-03-23 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Settings', '0001_initial'),
        ('Providers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('is_finish', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_payment', models.CharField(max_length=90)),
                ('is_cash_payment', models.BooleanField()),
                ('is_finish', models.BooleanField()),
                ('gain_seller', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gain_business', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gain_operational', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='Sales.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Settings.paymentmethod')),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('last_name', models.CharField(max_length=90)),
                ('identification', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20, unique=True)),
                ('address', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='Settings.gender')),
                ('identification_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='Settings.idtype')),
            ],
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('gain_seller', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gain_business', models.DecimalField(decimal_places=2, max_digits=9)),
                ('gain_operational', models.DecimalField(decimal_places=2, max_digits=9)),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Providers.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sales.sale')),
            ],
        ),
        migrations.AddField(
            model_name='sale',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sales', to='Sales.seller'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Providers.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ManyToManyField(related_name='orders', through='Sales.OrderProduct', to='Providers.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Sales.seller'),
        ),
    ]
