# Generated by Django 4.1 on 2024-02-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0002_remove_purchaseproduct_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='gain',
            new_name='gain_business',
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='gain_seller',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
